import jsPDF from "jspdf";
import "jspdf-autotable";
import * as XLSX from 'xlsx';

/**
 * Exports raw JSON data to an Excel file.
 * @param {Array} data - Array of objects to export.
 * @param {String} fileName - Name of the file without extension.
 * @param {String} sheetName - Name of the worksheet.
 */
export const exportToExcel = (data, fileName = "Report", sheetName = "Data") => {
  if (!data || data.length === 0) return;

  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);

  // Auto-width columns based on key length
  const keys = Object.keys(data[0]);
  const wscols = keys.map(key => ({ wch: Math.max(key.length + 5, 20) }));
  worksheet["!cols"] = wscols;

  XLSX.writeFile(workbook, `${fileName}_${new Date().toISOString().split('T')[0]}.xlsx`);
};

/**
 * Generates a professional PDF report with header, info box, stats, and table.
 * @param {Object} config - Configuration object.
 */
export const generatePDFReport = ({
  title = "REPORT",
  subTitle = "",
  generatedBy = "System",
  filters = [], // Array of { label: "Dept", value: "CSE" }
  stats = [],   // Array of { label: "Total", value: 10, color: [r,g,b] }
  tableHeaders = [],
  tableData = [],
  fileName = "Report"
}) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const today = new Date().toLocaleDateString("en-IN");

  // --- 1. Header Design ---
  doc.setFillColor(67, 56, 202); // Indigo 700
  doc.rect(0, 0, pageWidth, 40, "F");

  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text(title.toUpperCase(), 14, 20);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(subTitle, 14, 28);
  doc.text(`Generated By: ${generatedBy}  |  Date: ${today}`, 14, 34);

  // --- 2. Filter Summary Box ---
  if (filters.length > 0) {
    doc.setDrawColor(220, 220, 220);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, 45, pageWidth - 28, 22, 2, 2, "FD");

    let xPos = 20;
    const spacing = (pageWidth - 40) / filters.length;

    filters.forEach((filter) => {
      doc.setTextColor(100, 100, 100);
      doc.setFontSize(8);
      doc.text(filter.label.toUpperCase(), xPos, 52);

      doc.setTextColor(0, 0, 0);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.text(String(filter.value), xPos, 58);

      xPos += spacing;
    });
  }

  // --- 3. Statistical Dashboard ---
  let startY = 80;
  if (stats.length > 0) {
    const statY = 75;
    const boxWidth = (pageWidth - 28) / stats.length;
    let xPos = 14;

    stats.forEach((stat) => {
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.setFont("helvetica", "normal");
      doc.text(stat.label.toUpperCase(), xPos, statY);

      doc.setFontSize(14);
      doc.setTextColor(...(stat.color || [0, 0, 0])); // Default black if no color
      doc.setFont("helvetica", "bold");
      doc.text(String(stat.value), xPos, statY + 7);

      xPos += boxWidth;
    });
    startY = 90;
  }

  // --- 4. Table ---
  doc.autoTable({
    startY: startY,
    head: [tableHeaders],
    body: tableData,
    theme: 'grid',
    styles: {
      fontSize: 9,
      cellPadding: 3,
      valign: 'middle',
      lineWidth: 0.1,
      lineColor: [230, 230, 230]
    },
    headStyles: {
      fillColor: [67, 56, 202],
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [249, 250, 255]
    },
    didDrawPage: function (data) {
      const pageCount = doc.internal.getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Page ${pageCount}`,
        pageWidth - 20,
        doc.internal.pageSize.height - 10,
        { align: 'right' }
      );
    }
  });

  const now = new Date();

  const pad = (n) => String(n).padStart(2, '0');

  const getOrdinal = (n) => {
    if (n > 3 && n < 21) return 'th';
    switch (n % 10) {
      case 1: return 'st';
      case 2: return 'nd';
      case 3: return 'rd';
      default: return 'th';
    }
  };

  const months = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'];

  const formatted =
    `${now.getDate()}${getOrdinal(now.getDate())}-` +
    `${months[now.getMonth()]}-` +
    `${now.getFullYear()}_` +
    `${pad(now.getHours())}-` +
    `${pad(now.getMinutes())}-` +
    `${pad(now.getSeconds())}`;

  doc.save(`${fileName}_${formatted}.pdf`);

};